server:
    port: 8084
    
    
spring:
    application:
            name: API-GATEWAY    
        
    cloud:
      gateway:
        routes:
            - id: USER-SERVICE
              uri: lb://USER-SERVICE 
              predicates:
              - Path=/user/**
              
            - id: BLOG-SERVICE
              uri: lb://BLOG-SERVICE 
              predicates:
              - Path=/blogs/**
           
            - id: COMMENT-SERVICE
              uri: lb://COMMENT-SERVICE 
              predicates:
              - Path=/comments/**
         
            
eureka:
    instance:
         prefer-ip-address: true
    client:
      register-with-eureka: true
      fetch-registry: true  
      service-url:
           defaultZone: http://localhost:8761/eureka            