
server:
     port: 8081
  
spring:
   datasource:
        url: jdbc:mysql://localhost:3306/bloguser
        driver-class-name: com.mysql.cj.jdbc.Driver
        username: root
        password: root    
   
   application:
    name: USER-SERVICE
   jpa:
     hibernate:
         ddl-auto: update
     show-sql: true     
        
   config:
    import: configserver:http://localhost:8085
     

management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
         web:
           exposure:
              include: health
            
  endpoint:          
        health:      
          show-details: always

resilience4j:
  circuitbreaker:
    instances:
      blogCommentBreaker:
        registerHealthIndicator: true
        eventConsumerBufferSize: 10
        failureRateThreshold: 50
        minimumNumberOfCalls: 5
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 6s
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        slidingWindowType: COUNT_BASED         
        
        
  retry:
     instances:
          blogCommentService:
            max-attempts: 3
            wait-duration: 5s
                