
server:
     port: 8082
  

spring:
   datasource:
        url: jdbc:mysql://localhost:3306/blogpost
        driver-class-name: com.mysql.cj.jdbc.Driver
        username: root
        password: root    
   application:
         name: BLOG-SERVICE
   config:
    import: configserver:http://localhost:8085      
         
   jpa:
     hibernate:
         ddl-auto: update
     show-sql: true  
        
     