
server:
     port: 8083
  

spring:
   datasource:
        url: jdbc:mysql://localhost:3306/blogcomment
        driver-class-name: com.mysql.cj.jdbc.Driver
        username: root
        password: root    
   
   application:
         name: COMMENT-SERVICE
   config:
    import: configserver:http://localhost:8085
   
   jpa:
     hibernate:
         ddl-auto: update
     show-sql: true     
        